[project]
name = "finance-analysis"
authors = ["Author Name: <tomerroditi1@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.setuptools.dynamic]
version = {attr = "src.__version__"}

[tool.pytest.ini_options]
markers = [
    "sensitive: marks tests that pulls sensitive data from the internet",
]

[tool.poetry]
name = "finance-analysis"
version = "0.1.0"
description = ""
authors = ["Author Name: <tomerroditi1@gmail.com>"]

[tool.poetry.dependencies]
python = "==3.11"
pandas = "==2.2.1"
pytest = "==8.1.1"
Faker = "==24.3.0"
streamlit = "==1.33.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

