from scraper.providers.banks import (
    BeinleumiScraper,
    DiscountScraper,
    HapoalimScraper,
    LeumiScraper,
    MassadScraper,
    MercantileScraper,
    MizrahiScraper,
    OneZeroScraper,
    OtsarHahayalScraper,
    PagiScraper,
    UnionBankScraper,
    YahavScraper,
)
from scraper.providers.credit_cards import (
    AmexScraper,
    BehatsdaaScraper,
    BeyahadBishvilhaScraper,
    IsracardScraper,
    MaxScraper,
    VisaCalScraper,
)

__all__ = [
    "BeinleumiScraper",
    "DiscountScraper",
    "HapoalimScraper",
    "LeumiScraper",
    "MassadScraper",
    "MercantileScraper",
    "MizrahiScraper",
    "OneZeroScraper",
    "OtsarHahayalScraper",
    "PagiScraper",
    "UnionBankScraper",
    "YahavScraper",
    "AmexScraper",
    "BehatsdaaScraper",
    "BeyahadBishvilhaScraper",
    "IsracardScraper",
    "MaxScraper",
    "VisaCalScraper",
]
