"""Security middlewares: body-size cap, Host allowlist, remote token, CSRF, headers.

Their settings are read from the environment when this module is imported,
so ``backend.main`` imports it only after loading ``.env``. Each middleware
reads the module-level settings at request time, which is what lets tests
monkeypatch them.
"""

import logging
import os

from fastapi import Request
from fastapi.responses import JSONResponse, Response
from starlette.middleware.base import RequestResponseEndpoint

from backend.runtime import is_vercel
from backend.utils import auth

logger = logging.getLogger(__name__)

# A wildcard origin (``*``) may never be combined with
# ``allow_credentials=True`` — browsers reject such responses, and the
# combination would also permit any site to read authenticated responses.
# The Vite dev origin is a default only outside production: a production
# server serves its own SPA same-origin, and trusting :5173 there would hand
# whatever else runs on Vite's default port full read/write access.
_IS_PRODUCTION = os.getenv("ENVIRONMENT", "development").lower() == "production"
CORS_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ORIGINS",
        "" if _IS_PRODUCTION else "http://localhost:5173,http://127.0.0.1:5173",
    ).split(",")
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = "*" not in CORS_ORIGINS

# Cap request body size to mitigate memory-exhaustion DoS. 10 MB comfortably
# covers any JSON payload this app exchanges while blocking multi-GB bodies.
_MAX_REQUEST_BYTES = int(os.getenv("MAX_REQUEST_BYTES", str(10 * 1024 * 1024)))

# Methods that may carry a body. Bodiless methods skip the streaming path so
# a plain GET never waits on a request-body message.
_BODY_METHODS = frozenset({"POST", "PUT", "PATCH", "DELETE"})

# Host-header allowlist — blocks DNS-rebinding attacks, where a malicious
# website re-points its own domain at 127.0.0.1 so the victim's browser can
# reach this API "same-origin" (CORS never kicks in). Such requests arrive
# from loopback but carry the attacker's hostname in the Host header.
# Extra hostnames (Tailscale name, LAN IP) come from the ALLOWED_HOSTS env
# var; "*" disables the check (used behind trusted proxies, e.g. Vercel).
_allowed_hosts = auth.build_allowed_hosts()

# Token auth for remote clients. Loopback connections (the desktop app,
# dev servers, the Vite proxy) are trusted — unless a local reverse proxy
# relayed them from elsewhere. Those, like `./start.sh prod`'s tailnet share,
# pass only when `tailscale serve` vouches for an allowlisted tailnet user
# (TAILNET_ALLOWED_USERS) — and only on the loopback port reserved for it
# (TAILNET_INGRESS_PORT), since any other local proxy would relay a forged
# Tailscale-User-Login header untouched. Anything else — e.g. a phone hitting
# `./start.sh prod` bound beyond localhost — must present
# `Authorization: Bearer <token>` on /api requests. The token comes from
# FAD_API_TOKEN or `<user-dir>/api_token` (generated by start.sh when
# exposing); with no token configured, remote clients are denied outright.
# /api/* is guarded plus the OpenAPI/docs endpoints: the static SPA shell
# contains no data (and the frontend picks the token up from a one-time
# `?apiToken=` URL parameter), but the schema enumerates every route, and
# docs stay enabled whenever ENVIRONMENT isn't "production" — e.g. a dev
# server someone bound to 0.0.0.0.
_DOC_PATHS = frozenset({"/openapi.json", "/docs", "/redoc"})
_tailnet_users = auth.build_tailnet_users()
_tailnet_ingress_port = auth.build_tailnet_ingress_port()


def _too_large() -> JSONResponse:
    """Build the 413 response for an over-cap request body.

    Returns
    -------
    JSONResponse
        ``413 {"detail": "Request body too large"}``.
    """
    return JSONResponse(status_code=413, content={"detail": "Request body too large"})


async def limit_request_size(
    request: Request, call_next: RequestResponseEndpoint
) -> Response:
    """Reject requests whose body exceeds ``MAX_REQUEST_BYTES``.

    A declared ``Content-Length`` is checked up front. Chunked bodies carry
    no such header, so their bytes are counted while the body is consumed and
    the request is aborted the moment the cap is passed rather than being
    buffered and parsed in full.

    Parameters
    ----------
    request : Request
        Incoming request.
    call_next : RequestResponseEndpoint
        The rest of the middleware stack.

    Returns
    -------
    Response
        400 for a malformed ``Content-Length``, 413 over the cap, otherwise
        the downstream response.
    """
    content_length = request.headers.get("content-length")
    if content_length is not None:
        try:
            declared = int(content_length)
        except ValueError:
            return JSONResponse(
                status_code=400,
                content={"detail": "Invalid Content-Length header"},
            )
        if declared > _MAX_REQUEST_BYTES:
            return _too_large()
        return await call_next(request)

    if request.method not in _BODY_METHODS:
        return await call_next(request)

    chunks: list[bytes] = []
    received = 0
    async for chunk in request.stream():
        received += len(chunk)
        if received > _MAX_REQUEST_BYTES:
            return _too_large()
        chunks.append(chunk)

    # Hand the buffered body to the rest of the stack: Starlette's
    # BaseHTTPMiddleware replays ``_body`` to the downstream app when it is
    # set, so consuming the stream here stays invisible to the endpoint.
    request._body = b"".join(chunks)
    return await call_next(request)


async def enforce_host_allowlist(
    request: Request, call_next: RequestResponseEndpoint
) -> Response:
    """Reject requests whose Host header is not on the allowlist.

    Parameters
    ----------
    request : Request
        Incoming request.
    call_next : RequestResponseEndpoint
        The rest of the middleware stack.

    Returns
    -------
    Response
        400 for a foreign Host, otherwise the downstream response.
    """
    if is_vercel():
        return await call_next(request)
    if not auth.host_allowed(request.headers.get("host"), _allowed_hosts):
        return JSONResponse(
            status_code=400,
            content={"detail": "Invalid Host header"},
        )
    return await call_next(request)


def _needs_remote_token(path: str) -> bool:
    """Return whether ``path`` is guarded by the remote-client token check.

    Parameters
    ----------
    path : str
        Request URL path.

    Returns
    -------
    bool
        ``True`` for ``/api/*`` and the OpenAPI/docs endpoints.
    """
    return path.startswith(("/api/", "/docs/")) or path in _DOC_PATHS


async def require_token_for_remote_clients(
    request: Request, call_next: RequestResponseEndpoint
) -> Response:
    """Require a bearer token on /api and docs requests from non-local clients.

    Parameters
    ----------
    request : Request
        Incoming request.
    call_next : RequestResponseEndpoint
        The rest of the middleware stack.

    Returns
    -------
    Response
        401 for an untrusted client without a valid token, otherwise the
        downstream response.
    """
    if (
        is_vercel()
        or not _needs_remote_token(request.url.path)
        or request.method == "OPTIONS"
    ):
        return await call_next(request)
    client_host = request.client.host if request.client else None
    if auth.is_trusted_client(client_host):
        if not auth.is_proxied_request(request.headers):
            return await call_next(request)
        if auth.arrived_on_tailnet_ingress(
            request.scope.get("server"), _tailnet_ingress_port
        ) and auth.tailnet_user_allowed(
            request.headers.get("tailscale-user-login"), _tailnet_users
        ):
            return await call_next(request)
    supplied = auth.extract_bearer_token(request.headers.get("authorization"))
    if auth.token_matches(supplied, auth.get_api_token()):
        return await call_next(request)
    return JSONResponse(
        status_code=401,
        content={"detail": "Remote access requires a valid API token"},
    )


async def enforce_same_origin_for_writes(
    request: Request, call_next: RequestResponseEndpoint
) -> Response:
    """Reject state-changing /api requests carrying a foreign Origin.

    CSRF guard. Loopback clients are trusted by connection, so every website
    the user visits can also reach this API from their browser. CORS only
    stops the attacker *reading* the response — a cross-origin POST still
    executes, and a body sent with no Content-Type (a Blob with an empty
    type) is parsed by FastAPI as JSON, dodging the preflight that
    application/json would have forced. So state-changing requests must carry
    a same-site Origin, or none at all (curl, the desktop app, and other
    non-browser clients send none and cannot be driven by a hostile page).

    Parameters
    ----------
    request : Request
        Incoming request.
    call_next : RequestResponseEndpoint
        The rest of the middleware stack.

    Returns
    -------
    Response
        403 for a cross-origin write, otherwise the downstream response.
    """
    if (
        is_vercel()
        or request.method not in auth.UNSAFE_METHODS
        or not request.url.path.startswith("/api/")
    ):
        return await call_next(request)
    origin = request.headers.get("origin")
    if not auth.origin_allowed(origin, request.headers.get("host"), CORS_ORIGINS):
        logger.warning(
            "Blocked cross-origin %s %s from Origin %r",
            request.method,
            request.url.path,
            origin,
        )
        return JSONResponse(
            status_code=403,
            content={"detail": "Cross-origin request rejected"},
        )
    return await call_next(request)


async def add_security_headers(
    request: Request, call_next: RequestResponseEndpoint
) -> Response:
    """Apply conservative security headers to every response.

    Parameters
    ----------
    request : Request
        Incoming request.
    call_next : RequestResponseEndpoint
        The rest of the middleware stack.

    Returns
    -------
    Response
        The downstream response with the headers set where absent.
    """
    response = await call_next(request)
    response.headers.setdefault("X-Content-Type-Options", "nosniff")
    response.headers.setdefault("X-Frame-Options", "DENY")
    response.headers.setdefault("Referrer-Policy", "no-referrer")
    response.headers.setdefault(
        "Permissions-Policy",
        "geolocation=(), microphone=(), camera=(), payment=()",
    )
    # HSTS is only meaningful over HTTPS; emit it when the request was TLS.
    if request.url.scheme == "https":
        response.headers.setdefault(
            "Strict-Transport-Security",
            "max-age=31536000; includeSubDomains",
        )
    return response
